### PR TITLE
Use relative path to style and script files

### PR DESCRIPTION
**Pull request by fleuronvilik**
Hi!
You are currently using absolute path to loas `style.css` and `app4.js`.
Your project will display well only on your machine.

### CODE REVIEW

**Comment by fleuronvilik** [comment]
https://fleuronvilik.github.io/Quiz-Game/

**Comment by AdodoolaO** [comment]
Thank you so much for your help. I'm working but I'm going to reveal my code and make the changes 🙏🏽🙏🏽

**Comment by fleuronvilik** [comment]
You're welcome!

**Review by AdodoolaO — APPROVED** [review]

**Review by AdodoolaO — APPROVED** [review]

**Review by AdodoolaO — APPROVED** [review]

**Review by AdodoolaO — APPROVED** [review]

**Comment by AdodoolaO** [comment]
Thank you again. Would it be possible to explain the shuffle function you created?

**Comment by fleuronvilik** [comment]
> Thank you again. Would it be possible to explain the shuffle function you created?

Yes. Before, the first choice is always the correct one.
The function takes an array of answers and pick randomly tone answer to add to a new, initially empty array.
This is repeated until the array passed in is empty. The new one is then returned with the same answers, but in random order so that the correct answer is no longer always the first choice.

I use these array methods: 
- [.concat()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat)
- [.splice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice)

Let me know of others bits of code you didn't understand.

**Comment by AdodoolaO** [comment]
Thank you i understand!

**Pull request merged**
